export const MAP_IMAGE = "/ar-targets/dien_bien_phu_map.jpg";

export const actionTypes = [
  "highlight",
  "pulse-ring",
  "attack-arrow",
  "hand-guide",
  "airplane",
  "bomb-drop",
  "explosion",
  "show-label",
  "open-point",
  "play-video",
];

export const defaultArMarkers = [
  { id: "him-lam", label: "Him Lam", x: 43.7, y: 58.0, color: "#ef4444", markerScale: 1, videoPath: "" },
  { id: "muong-thanh", label: "Muong Thanh", x: 27.6, y: 75.5, color: "#f59e0b", markerScale: 1, videoPath: "" },
  { id: "tan-thanh", label: "Tan Thanh", x: 31.8, y: 68.3, color: "#8b5cf6", markerScale: 1, videoPath: "" },
  { id: "thanh-minh", label: "Thanh Minh", x: 69.4, y: 37.7, color: "#22c55e", markerScale: 1, videoPath: "" },
  { id: "ta-leng", label: "Ta Leng", x: 82.8, y: 69.9, color: "#38bdf8", markerScale: 1, videoPath: "" },
];

export const defaultMapCalibration = {
  offsetX: 0,
  offsetY: 0,
  scaleX: 1,
  scaleY: 1,
};

export const defaultArTimeline = [
  {
    id: "intro",
    title: "Audio mo dau sau Start",
    at: 0,
    duration: 18,
    audioPath: "/audio/01_intro.mp3",
    narration: "Sau khi bam Start AR, doc dan gioi thieu ban do va muc tieu dau tien.",
    autoPlayAfterStart: true,
    waitForPointClose: "",
    actions: [
      {
        id: "intro-highlight-him-lam",
        type: "pulse-ring",
        at: 2,
        duration: 8,
        pointId: "him-lam",
        label: "Muc tieu dau tien: Him Lam",
        color: "#ef4444",
        assetPath: "",
        position: "43.7,58",
        from: "",
        to: "",
        rotation: 0,
        scale: 1,
      },
      {
        id: "intro-attack-arrow",
        type: "attack-arrow",
        at: 5,
        duration: 9,
        pointId: "him-lam",
        label: "Mui tien cong vao Him Lam",
        color: "#22c55e",
        assetPath: "/ar-assets/attack-arrow.glb",
        position: "",
        from: "18,82",
        to: "43.7,58",
        rotation: 0,
        scale: 1,
      },
      {
        id: "intro-hand-guide",
        type: "hand-guide",
        at: 14,
        duration: 7,
        pointId: "thanh-minh",
        label: "Bam moc 2 de xem dien bien tiep theo",
        color: "#ffffff",
        assetPath: "/ar-assets/hand-pointer.glb",
        position: "69.4,37.7",
        from: "",
        to: "69.4,37.7",
        rotation: 0,
        scale: 1,
      },
    ],
  },
  {
    id: "after-him-lam",
    title: "Dan tiep sau khi tat tran Him Lam",
    at: 20,
    duration: 16,
    audioPath: "/audio/02_after_him_lam.mp3",
    narration: "Phat sau khi nguoi dung dong cua so tran Him Lam, dan sang moc tiep theo.",
    autoPlayAfterStart: false,
    waitForPointClose: "him-lam",
    actions: [
      {
        id: "after-him-lam-next",
        type: "pulse-ring",
        at: 1,
        duration: 8,
        pointId: "thanh-minh",
        label: "Moc tiep theo",
        color: "#22c55e",
        assetPath: "",
        position: "69.4,37.7",
        from: "",
        to: "",
        rotation: 0,
        scale: 1,
      },
    ],
  },
];
